[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"

# Compiler settings
solc_version = "0.8.24"
evm_version = "paris"
via_ir = false
optimizer = true
optimizer_runs = 200

# Remappings for OpenZeppelin
remappings = ["@openzeppelin/=lib/"]

# RPC Configuration
[rpc_endpoints]
sepolia = "${ETH_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# Fuzzing Configuration
[fuzz]
runs = 256
max_test_rejects = 65536

# Deployment
script = "script"

# Gas reporting
gas_reports = ["*"]
